### ISSUE TITLE
TODO: AdminCP

### ISSUE THREAD

**Issue by aromig** [aromig/ccg#3]
- [x] Edit Users
- [x] Edit Toons
- [ ] ~~Edit Run Reports~~
- [x] Edit Run Schedule
- [x] Edit Other Variables

**Comment by aromig** [comment]
Edit Run Reports - not in AdminCP now. Accessible from Victories page by original user and admins.
